static class EnumExtension
{
    public static readonly Dictionary<string, string> PropertyDataIdExtensions = new()
    {
        { "ProcSpell" , "SpellId" },
        { "PCAPRecordedParentLocation" , "ParentLocation" },
        { "PhysicsScript" , "PlayScript" },
        { "UseTargetSuccessAnimation" , "MotionCommand" },
        { "UseSound" , "Sound" },
        { "UseUserAnimation" , "MotionCommand" },
        { "UseTargetAnimation" , "MotionCommand" },
        { "BlueSurgeSpell" , "SpellId" },
        { "RedSurgeSpell" , "SpellId" },
        { "DeathSpell" , "SpellId" },
        { "ItemSpecializedOnly" , "Skill" },
        { "PCAPRecordedDefaultScript" , "MotionCommand" },
        { "InitMotion" , "MotionCommand" },
        { "ActivationSound" , "Sound" },
        { "ActivationAnimation" , "MotionCommand" },
        { "ItemSkillLimit" , "Skill" },
        { "YellowSurgeSpell" , "SpellId" },
        { "Spell", "SpellId" },
        { "RestrictionEffect" , "PlayScript" },
        { "UseTargetFailureAnimation" , "MotionCommand" }
    };

    public static readonly Dictionary<string, string> PropertyIntExtensions = new()
    {
        { "WieldSkillType" , "Skill" },
        { "PaletteTemplate" , "PaletteTemplate" },
        { "Faction1Bits" , "FactionBits" },
        { "HookType" , "HookType" },
        { "FriendType" , "CreatureType" },
        { "WeaponSkill" , "Skill" },
        { "AppraisalItemSkill" , "Skill" },
        { "CreatureType" , "CreatureType" },
        { "ItemType" , "ItemType" },
        { "WieldRequirements" , "WieldRequirement" },
        { "CombatUse" , "CombatUse" },
        { "Gender" , "Gender" },
        { "ItemXpStyle" , "ItemXpStyle" },
        { "ImbuedEffect2" , "ImbuedEffectType" },
        { "MaterialType" , "MaterialType" },
        { "HeritageSpecificArmor" , "HeritageGroup" },
        { "DefaultCombatStyle" , "CombatStyle" },
        { "ImbuedEffect5" , "ImbuedEffectType" },
        { "Placement" , "Placement" },
        { "HookGroup" , "HookGroupType" },
        { "ImbuedEffect4" , "ImbuedEffectType" },
        { "ImbuedEffect3" , "ImbuedEffectType" },
        { "EquipmentSetId" , "EquipmentSet" },
        { "ImbuedEffect" , "ImbuedEffectType" },
        { "ParentLocation" , "ParentLocation" },
        { "PlacementPosition" , "Placement" },
        { "SlayerCreatureType" , "CreatureType" },
        { "PCAPRecordedPlacement" , "Placement" },
        { "CombatMode" , "CombatMode" },
        { "UseRequiresSkill" , "Skill" },
        { "BoosterEnum" , "PropertyAttribute2nd" },
        { "SkillToBeAltered" , "Skill" },
        { "PlayerKillerStatus" , "PlayerKillerStatus" },
        { "RadarBlipColor" , "RadarColor" },
        { "AttackType" , "AttackType" },
        { "Hatred2Bits" , "FactionBits" },
        { "Faction3Bits" , "FactionBits" },
        { "Bonded" , "BondedStatus" },
        { "GeneratorType" , "GeneratorType" },
        { "AmmoType" , "AmmoType" },
        { "HouseStatus" , "HouseStatus" },
        { "ChannelsAllowed" , "Channel" },
        { "AiAllowedCombatStyle" , "CombatStyle" },
        { "Faction2Bits" , "FactionBits" },
        { "Hatred3Bits" , "FactionBits" },
        { "WeaponType" , "WeaponType" },
        { "WieldSkillType4" , "Skill" },
        { "ResistanceModifierType" , "DamageType" },
        { "WieldSkillType2" , "Skill" },
        { "WieldSkillType3" , "Skill" },
        { "UseRequiresSkillSpec" , "Skill" },
        { "ActivationResponse" , "ActivationResponse" },
        { "HookItemType" , "ItemType" },
        { "ValidLocations" , "EquipMask" },
        { "SummoningMastery" , "SummoningMastery" },
        { "UiEffects" , "UiEffects" },
        { "ClothingPriority" , "CoverageMask" },
        { "HouseType" , "HouseType" },
        { "TargetType" , "ItemType" },
        { "Hatred1Bits" , "FactionBits" },
        { "GeneratorEndDestructionType" , "GeneratorDestruct" },
        { "PhysicsState" , "PhysicsState" },
        { "FoeType" , "CreatureType" },
        { "AetheriaBitfield" , "AetheriaBitfield" },
        { "GeneratorDestructionType" , "GeneratorDestruct" },
        { "ItemUseable" , "Usable" },
        { "UseCreatesContractId" , "ContractId" },
        { "DamageType" , "DamageType" },
        { "GeneratorTimeType" , "GeneratorTimeType" },
        { "HookPlacement" , "Placement" },
        { "PortalBitmask" , "PortalBitmask" },
        { "AttackHeight" , "AttackHeight" },
        { "AccountRequirements" , "SubscriptionStatus" },
        { "HeritageGroup" , "HeritageGroup" },
        { "WieldRequirements2" , "WieldRequirement" },
        { "CurrentWieldedLocation" , "EquipMask" },
        { "Attuned" , "AttunedStatus" },
        { "MerchandiseItemTypes" , "ItemType" },
        { "WieldRequirements3" , "WieldRequirement" },
        { "WieldRequirements4" , "WieldRequirement" },
        { "ArmorType" , "ArmorType" },
        { "ShowableOnRadar" , "RadarBehavior" },
        { "ChannelsActive" , "Channel" }
    };
}