// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PortalDatDB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PortalDatDB.proto</summary>
public static partial class PortalDatDBReflection {

  #region Descriptor
  /// <summary>File descriptor for PortalDatDB.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PortalDatDBReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFQb3J0YWxEYXREQi5wcm90byJ1CgVTa2lsbBIKCgJpZBgBIAEoDRINCgVh",
          "dHRyMRgCIAEoDRINCgVhdHRyMhgDIAEoDRIPCgdkaXZpc29yGAQgASgNEhMK",
          "C2Rlc2NyaXB0aW9uGAUgASgJEgwKBG5hbWUYBiABKAkSDgoGaWNvbklkGAcg",
          "ASgNIi8KEFhwTGlzdEVsZW1lbnRJbnQSDQoFbGV2ZWwYASABKAUSDAoEY29z",
          "dBgCIAEoDSIwChFYcExpc3RFbGVtZW50TG9uZxINCgVsZXZlbBgBIAEoBRIM",
          "CgRjb3N0GAIgASgEIo8DCghDb250cmFjdBIKCgJpZBgBIAEoDRIPCgd2ZXJz",
          "aW9uGAIgASgNEgwKBG5hbWUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkS",
          "HAoUZGVzY3JpcHRpb25fcHJvZ3Jlc3MYBSABKAkSFgoObmFtZV9ucGNfc3Rh",
          "cnQYBiABKAkSFAoMbmFtZV9ucGNfZW5kGAcgASgJEhkKEXF1ZXN0ZmxhZ19z",
          "dGFtcGVkGAggASgJEhkKEXF1ZXN0ZmxhZ19zdGFydGVkGAkgASgJEhoKEnF1",
          "ZXN0ZmxhZ19maW5pc2hlZBgKIAEoCRIaChJxdWVzdGZsYWdfcHJvZ3Jlc3MY",
          "CyABKAkSFwoPcXVlc3RmbGFnX3RpbWVyGAwgASgJEh0KFXF1ZXN0ZmxhZ19y",
          "ZXBlYXRfdGltZRgNIAEoCRIaChJsb2NhdGlvbl9ucGNfc3RhcnQYDiABKAkS",
          "GAoQbG9jYXRpb25fbnBjX2VuZBgPIAEoCRIbChNsb2NhdGlvbl9xdWVzdF9h",
          "cmVhGBAgASgJItUBChJTZWNvbmRhcnlBdHRyaWJ1dGUSHQoVaGVhbHRoX2F0",
          "dHJpYnV0ZV90eXBlGAEgASgNEiAKGGhlYWx0aF9hdHRyaWJ1dGVfZGl2aXNv",
          "chgCIAEoDRIeChZzdGFtaW5hX2F0dHJpYnV0ZV90eXBlGAMgASgNEiEKGXN0",
          "YW1pbmFfYXR0cmlidXRlX2Rpdmlzb3IYBCABKA0SGwoTbWFuYV9hdHRyaWJ1",
          "dGVfdHlwZRgFIAEoDRIeChZtYW5hX2F0dHJpYnV0ZV9kaXZpc29yGAYgASgN",
          "IskCCgtQb3J0YWxEYXREQhImCgthdHRyaWJ1dGVYcBgBIAMoCzIRLlhwTGlz",
          "dEVsZW1lbnRJbnQSIgoHdml0YWxYcBgCIAMoCzIRLlhwTGlzdEVsZW1lbnRJ",
          "bnQSKQoOdHJhaW5lZFNraWxsWHAYAyADKAsyES5YcExpc3RFbGVtZW50SW50",
          "Ei0KEnNwZWNpYWxpemVkU2tpbGxYcBgEIAMoCzIRLlhwTGlzdEVsZW1lbnRJ",
          "bnQSLAoQY2hhcmFjdGVyTGV2ZWxYcBgFIAMoCzISLlhwTGlzdEVsZW1lbnRM",
          "b25nEhYKBnNraWxscxgGIAMoCzIGLlNraWxsEhwKCWNvbnRyYWN0cxgHIAMo",
          "CzIJLkNvbnRyYWN0EjAKE3NlY29uZGFyeUF0dHJpYnV0ZXMYCCABKAsyEy5T",
          "ZWNvbmRhcnlBdHRyaWJ1dGViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Skill), global::Skill.Parser, new[]{ "Id", "Attr1", "Attr2", "Divisor", "Description", "Name", "IconId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::XpListElementInt), global::XpListElementInt.Parser, new[]{ "Level", "Cost" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::XpListElementLong), global::XpListElementLong.Parser, new[]{ "Level", "Cost" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Contract), global::Contract.Parser, new[]{ "Id", "Version", "Name", "Description", "DescriptionProgress", "NameNpcStart", "NameNpcEnd", "QuestflagStamped", "QuestflagStarted", "QuestflagFinished", "QuestflagProgress", "QuestflagTimer", "QuestflagRepeatTime", "LocationNpcStart", "LocationNpcEnd", "LocationQuestArea" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SecondaryAttribute), global::SecondaryAttribute.Parser, new[]{ "HealthAttributeType", "HealthAttributeDivisor", "StaminaAttributeType", "StaminaAttributeDivisor", "ManaAttributeType", "ManaAttributeDivisor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PortalDatDB), global::PortalDatDB.Parser, new[]{ "AttributeXp", "VitalXp", "TrainedSkillXp", "SpecializedSkillXp", "CharacterLevelXp", "Skills", "Contracts", "SecondaryAttributes" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Skill : pb::IMessage<Skill>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Skill> _parser = new pb::MessageParser<Skill>(() => new Skill());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Skill> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PortalDatDBReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Skill() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Skill(Skill other) : this() {
    id_ = other.id_;
    attr1_ = other.attr1_;
    attr2_ = other.attr2_;
    divisor_ = other.divisor_;
    description_ = other.description_;
    name_ = other.name_;
    iconId_ = other.iconId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Skill Clone() {
    return new Skill(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "attr1" field.</summary>
  public const int Attr1FieldNumber = 2;
  private uint attr1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Attr1 {
    get { return attr1_; }
    set {
      attr1_ = value;
    }
  }

  /// <summary>Field number for the "attr2" field.</summary>
  public const int Attr2FieldNumber = 3;
  private uint attr2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Attr2 {
    get { return attr2_; }
    set {
      attr2_ = value;
    }
  }

  /// <summary>Field number for the "divisor" field.</summary>
  public const int DivisorFieldNumber = 4;
  private uint divisor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Divisor {
    get { return divisor_; }
    set {
      divisor_ = value;
    }
  }

  /// <summary>Field number for the "description" field.</summary>
  public const int DescriptionFieldNumber = 5;
  private string description_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Description {
    get { return description_; }
    set {
      description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 6;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "iconId" field.</summary>
  public const int IconIdFieldNumber = 7;
  private uint iconId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint IconId {
    get { return iconId_; }
    set {
      iconId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Skill);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Skill other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Attr1 != other.Attr1) return false;
    if (Attr2 != other.Attr2) return false;
    if (Divisor != other.Divisor) return false;
    if (Description != other.Description) return false;
    if (Name != other.Name) return false;
    if (IconId != other.IconId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Attr1 != 0) hash ^= Attr1.GetHashCode();
    if (Attr2 != 0) hash ^= Attr2.GetHashCode();
    if (Divisor != 0) hash ^= Divisor.GetHashCode();
    if (Description.Length != 0) hash ^= Description.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (IconId != 0) hash ^= IconId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Attr1 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Attr1);
    }
    if (Attr2 != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Attr2);
    }
    if (Divisor != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Divisor);
    }
    if (Description.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Description);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Name);
    }
    if (IconId != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(IconId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Attr1 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Attr1);
    }
    if (Attr2 != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Attr2);
    }
    if (Divisor != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Divisor);
    }
    if (Description.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Description);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Name);
    }
    if (IconId != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(IconId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (Attr1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Attr1);
    }
    if (Attr2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Attr2);
    }
    if (Divisor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Divisor);
    }
    if (Description.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (IconId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IconId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Skill other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Attr1 != 0) {
      Attr1 = other.Attr1;
    }
    if (other.Attr2 != 0) {
      Attr2 = other.Attr2;
    }
    if (other.Divisor != 0) {
      Divisor = other.Divisor;
    }
    if (other.Description.Length != 0) {
      Description = other.Description;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.IconId != 0) {
      IconId = other.IconId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Attr1 = input.ReadUInt32();
          break;
        }
        case 24: {
          Attr2 = input.ReadUInt32();
          break;
        }
        case 32: {
          Divisor = input.ReadUInt32();
          break;
        }
        case 42: {
          Description = input.ReadString();
          break;
        }
        case 50: {
          Name = input.ReadString();
          break;
        }
        case 56: {
          IconId = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Attr1 = input.ReadUInt32();
          break;
        }
        case 24: {
          Attr2 = input.ReadUInt32();
          break;
        }
        case 32: {
          Divisor = input.ReadUInt32();
          break;
        }
        case 42: {
          Description = input.ReadString();
          break;
        }
        case 50: {
          Name = input.ReadString();
          break;
        }
        case 56: {
          IconId = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class XpListElementInt : pb::IMessage<XpListElementInt>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<XpListElementInt> _parser = new pb::MessageParser<XpListElementInt>(() => new XpListElementInt());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<XpListElementInt> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PortalDatDBReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XpListElementInt() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XpListElementInt(XpListElementInt other) : this() {
    level_ = other.level_;
    cost_ = other.cost_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XpListElementInt Clone() {
    return new XpListElementInt(this);
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 1;
  private int level_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "cost" field.</summary>
  public const int CostFieldNumber = 2;
  private uint cost_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Cost {
    get { return cost_; }
    set {
      cost_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as XpListElementInt);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(XpListElementInt other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Level != other.Level) return false;
    if (Cost != other.Cost) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Level != 0) hash ^= Level.GetHashCode();
    if (Cost != 0) hash ^= Cost.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Level != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Level);
    }
    if (Cost != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Cost);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Level != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Level);
    }
    if (Cost != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Cost);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
    }
    if (Cost != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Cost);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(XpListElementInt other) {
    if (other == null) {
      return;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.Cost != 0) {
      Cost = other.Cost;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Level = input.ReadInt32();
          break;
        }
        case 16: {
          Cost = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Level = input.ReadInt32();
          break;
        }
        case 16: {
          Cost = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class XpListElementLong : pb::IMessage<XpListElementLong>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<XpListElementLong> _parser = new pb::MessageParser<XpListElementLong>(() => new XpListElementLong());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<XpListElementLong> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PortalDatDBReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XpListElementLong() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XpListElementLong(XpListElementLong other) : this() {
    level_ = other.level_;
    cost_ = other.cost_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public XpListElementLong Clone() {
    return new XpListElementLong(this);
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 1;
  private int level_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "cost" field.</summary>
  public const int CostFieldNumber = 2;
  private ulong cost_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Cost {
    get { return cost_; }
    set {
      cost_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as XpListElementLong);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(XpListElementLong other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Level != other.Level) return false;
    if (Cost != other.Cost) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Level != 0) hash ^= Level.GetHashCode();
    if (Cost != 0UL) hash ^= Cost.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Level != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Level);
    }
    if (Cost != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Cost);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Level != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Level);
    }
    if (Cost != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Cost);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
    }
    if (Cost != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Cost);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(XpListElementLong other) {
    if (other == null) {
      return;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.Cost != 0UL) {
      Cost = other.Cost;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Level = input.ReadInt32();
          break;
        }
        case 16: {
          Cost = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Level = input.ReadInt32();
          break;
        }
        case 16: {
          Cost = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Contract : pb::IMessage<Contract>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Contract> _parser = new pb::MessageParser<Contract>(() => new Contract());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Contract> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PortalDatDBReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Contract() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Contract(Contract other) : this() {
    id_ = other.id_;
    version_ = other.version_;
    name_ = other.name_;
    description_ = other.description_;
    descriptionProgress_ = other.descriptionProgress_;
    nameNpcStart_ = other.nameNpcStart_;
    nameNpcEnd_ = other.nameNpcEnd_;
    questflagStamped_ = other.questflagStamped_;
    questflagStarted_ = other.questflagStarted_;
    questflagFinished_ = other.questflagFinished_;
    questflagProgress_ = other.questflagProgress_;
    questflagTimer_ = other.questflagTimer_;
    questflagRepeatTime_ = other.questflagRepeatTime_;
    locationNpcStart_ = other.locationNpcStart_;
    locationNpcEnd_ = other.locationNpcEnd_;
    locationQuestArea_ = other.locationQuestArea_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Contract Clone() {
    return new Contract(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 2;
  private uint version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Version {
    get { return version_; }
    set {
      version_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 3;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "description" field.</summary>
  public const int DescriptionFieldNumber = 4;
  private string description_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Description {
    get { return description_; }
    set {
      description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "description_progress" field.</summary>
  public const int DescriptionProgressFieldNumber = 5;
  private string descriptionProgress_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DescriptionProgress {
    get { return descriptionProgress_; }
    set {
      descriptionProgress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "name_npc_start" field.</summary>
  public const int NameNpcStartFieldNumber = 6;
  private string nameNpcStart_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NameNpcStart {
    get { return nameNpcStart_; }
    set {
      nameNpcStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "name_npc_end" field.</summary>
  public const int NameNpcEndFieldNumber = 7;
  private string nameNpcEnd_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NameNpcEnd {
    get { return nameNpcEnd_; }
    set {
      nameNpcEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "questflag_stamped" field.</summary>
  public const int QuestflagStampedFieldNumber = 8;
  private string questflagStamped_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string QuestflagStamped {
    get { return questflagStamped_; }
    set {
      questflagStamped_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "questflag_started" field.</summary>
  public const int QuestflagStartedFieldNumber = 9;
  private string questflagStarted_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string QuestflagStarted {
    get { return questflagStarted_; }
    set {
      questflagStarted_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "questflag_finished" field.</summary>
  public const int QuestflagFinishedFieldNumber = 10;
  private string questflagFinished_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string QuestflagFinished {
    get { return questflagFinished_; }
    set {
      questflagFinished_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "questflag_progress" field.</summary>
  public const int QuestflagProgressFieldNumber = 11;
  private string questflagProgress_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string QuestflagProgress {
    get { return questflagProgress_; }
    set {
      questflagProgress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "questflag_timer" field.</summary>
  public const int QuestflagTimerFieldNumber = 12;
  private string questflagTimer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string QuestflagTimer {
    get { return questflagTimer_; }
    set {
      questflagTimer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "questflag_repeat_time" field.</summary>
  public const int QuestflagRepeatTimeFieldNumber = 13;
  private string questflagRepeatTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string QuestflagRepeatTime {
    get { return questflagRepeatTime_; }
    set {
      questflagRepeatTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "location_npc_start" field.</summary>
  public const int LocationNpcStartFieldNumber = 14;
  private string locationNpcStart_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LocationNpcStart {
    get { return locationNpcStart_; }
    set {
      locationNpcStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "location_npc_end" field.</summary>
  public const int LocationNpcEndFieldNumber = 15;
  private string locationNpcEnd_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LocationNpcEnd {
    get { return locationNpcEnd_; }
    set {
      locationNpcEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "location_quest_area" field.</summary>
  public const int LocationQuestAreaFieldNumber = 16;
  private string locationQuestArea_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LocationQuestArea {
    get { return locationQuestArea_; }
    set {
      locationQuestArea_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Contract);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Contract other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Version != other.Version) return false;
    if (Name != other.Name) return false;
    if (Description != other.Description) return false;
    if (DescriptionProgress != other.DescriptionProgress) return false;
    if (NameNpcStart != other.NameNpcStart) return false;
    if (NameNpcEnd != other.NameNpcEnd) return false;
    if (QuestflagStamped != other.QuestflagStamped) return false;
    if (QuestflagStarted != other.QuestflagStarted) return false;
    if (QuestflagFinished != other.QuestflagFinished) return false;
    if (QuestflagProgress != other.QuestflagProgress) return false;
    if (QuestflagTimer != other.QuestflagTimer) return false;
    if (QuestflagRepeatTime != other.QuestflagRepeatTime) return false;
    if (LocationNpcStart != other.LocationNpcStart) return false;
    if (LocationNpcEnd != other.LocationNpcEnd) return false;
    if (LocationQuestArea != other.LocationQuestArea) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Version != 0) hash ^= Version.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Description.Length != 0) hash ^= Description.GetHashCode();
    if (DescriptionProgress.Length != 0) hash ^= DescriptionProgress.GetHashCode();
    if (NameNpcStart.Length != 0) hash ^= NameNpcStart.GetHashCode();
    if (NameNpcEnd.Length != 0) hash ^= NameNpcEnd.GetHashCode();
    if (QuestflagStamped.Length != 0) hash ^= QuestflagStamped.GetHashCode();
    if (QuestflagStarted.Length != 0) hash ^= QuestflagStarted.GetHashCode();
    if (QuestflagFinished.Length != 0) hash ^= QuestflagFinished.GetHashCode();
    if (QuestflagProgress.Length != 0) hash ^= QuestflagProgress.GetHashCode();
    if (QuestflagTimer.Length != 0) hash ^= QuestflagTimer.GetHashCode();
    if (QuestflagRepeatTime.Length != 0) hash ^= QuestflagRepeatTime.GetHashCode();
    if (LocationNpcStart.Length != 0) hash ^= LocationNpcStart.GetHashCode();
    if (LocationNpcEnd.Length != 0) hash ^= LocationNpcEnd.GetHashCode();
    if (LocationQuestArea.Length != 0) hash ^= LocationQuestArea.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Version != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Version);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (Description.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Description);
    }
    if (DescriptionProgress.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(DescriptionProgress);
    }
    if (NameNpcStart.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(NameNpcStart);
    }
    if (NameNpcEnd.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(NameNpcEnd);
    }
    if (QuestflagStamped.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(QuestflagStamped);
    }
    if (QuestflagStarted.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(QuestflagStarted);
    }
    if (QuestflagFinished.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(QuestflagFinished);
    }
    if (QuestflagProgress.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(QuestflagProgress);
    }
    if (QuestflagTimer.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(QuestflagTimer);
    }
    if (QuestflagRepeatTime.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(QuestflagRepeatTime);
    }
    if (LocationNpcStart.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(LocationNpcStart);
    }
    if (LocationNpcEnd.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(LocationNpcEnd);
    }
    if (LocationQuestArea.Length != 0) {
      output.WriteRawTag(130, 1);
      output.WriteString(LocationQuestArea);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (Version != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Version);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (Description.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Description);
    }
    if (DescriptionProgress.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(DescriptionProgress);
    }
    if (NameNpcStart.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(NameNpcStart);
    }
    if (NameNpcEnd.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(NameNpcEnd);
    }
    if (QuestflagStamped.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(QuestflagStamped);
    }
    if (QuestflagStarted.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(QuestflagStarted);
    }
    if (QuestflagFinished.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(QuestflagFinished);
    }
    if (QuestflagProgress.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(QuestflagProgress);
    }
    if (QuestflagTimer.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(QuestflagTimer);
    }
    if (QuestflagRepeatTime.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(QuestflagRepeatTime);
    }
    if (LocationNpcStart.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(LocationNpcStart);
    }
    if (LocationNpcEnd.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(LocationNpcEnd);
    }
    if (LocationQuestArea.Length != 0) {
      output.WriteRawTag(130, 1);
      output.WriteString(LocationQuestArea);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (Version != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Description.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
    }
    if (DescriptionProgress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DescriptionProgress);
    }
    if (NameNpcStart.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNpcStart);
    }
    if (NameNpcEnd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NameNpcEnd);
    }
    if (QuestflagStamped.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestflagStamped);
    }
    if (QuestflagStarted.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestflagStarted);
    }
    if (QuestflagFinished.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestflagFinished);
    }
    if (QuestflagProgress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestflagProgress);
    }
    if (QuestflagTimer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestflagTimer);
    }
    if (QuestflagRepeatTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(QuestflagRepeatTime);
    }
    if (LocationNpcStart.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LocationNpcStart);
    }
    if (LocationNpcEnd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LocationNpcEnd);
    }
    if (LocationQuestArea.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(LocationQuestArea);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Contract other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Version != 0) {
      Version = other.Version;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Description.Length != 0) {
      Description = other.Description;
    }
    if (other.DescriptionProgress.Length != 0) {
      DescriptionProgress = other.DescriptionProgress;
    }
    if (other.NameNpcStart.Length != 0) {
      NameNpcStart = other.NameNpcStart;
    }
    if (other.NameNpcEnd.Length != 0) {
      NameNpcEnd = other.NameNpcEnd;
    }
    if (other.QuestflagStamped.Length != 0) {
      QuestflagStamped = other.QuestflagStamped;
    }
    if (other.QuestflagStarted.Length != 0) {
      QuestflagStarted = other.QuestflagStarted;
    }
    if (other.QuestflagFinished.Length != 0) {
      QuestflagFinished = other.QuestflagFinished;
    }
    if (other.QuestflagProgress.Length != 0) {
      QuestflagProgress = other.QuestflagProgress;
    }
    if (other.QuestflagTimer.Length != 0) {
      QuestflagTimer = other.QuestflagTimer;
    }
    if (other.QuestflagRepeatTime.Length != 0) {
      QuestflagRepeatTime = other.QuestflagRepeatTime;
    }
    if (other.LocationNpcStart.Length != 0) {
      LocationNpcStart = other.LocationNpcStart;
    }
    if (other.LocationNpcEnd.Length != 0) {
      LocationNpcEnd = other.LocationNpcEnd;
    }
    if (other.LocationQuestArea.Length != 0) {
      LocationQuestArea = other.LocationQuestArea;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Version = input.ReadUInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          Description = input.ReadString();
          break;
        }
        case 42: {
          DescriptionProgress = input.ReadString();
          break;
        }
        case 50: {
          NameNpcStart = input.ReadString();
          break;
        }
        case 58: {
          NameNpcEnd = input.ReadString();
          break;
        }
        case 66: {
          QuestflagStamped = input.ReadString();
          break;
        }
        case 74: {
          QuestflagStarted = input.ReadString();
          break;
        }
        case 82: {
          QuestflagFinished = input.ReadString();
          break;
        }
        case 90: {
          QuestflagProgress = input.ReadString();
          break;
        }
        case 98: {
          QuestflagTimer = input.ReadString();
          break;
        }
        case 106: {
          QuestflagRepeatTime = input.ReadString();
          break;
        }
        case 114: {
          LocationNpcStart = input.ReadString();
          break;
        }
        case 122: {
          LocationNpcEnd = input.ReadString();
          break;
        }
        case 130: {
          LocationQuestArea = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          Version = input.ReadUInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          Description = input.ReadString();
          break;
        }
        case 42: {
          DescriptionProgress = input.ReadString();
          break;
        }
        case 50: {
          NameNpcStart = input.ReadString();
          break;
        }
        case 58: {
          NameNpcEnd = input.ReadString();
          break;
        }
        case 66: {
          QuestflagStamped = input.ReadString();
          break;
        }
        case 74: {
          QuestflagStarted = input.ReadString();
          break;
        }
        case 82: {
          QuestflagFinished = input.ReadString();
          break;
        }
        case 90: {
          QuestflagProgress = input.ReadString();
          break;
        }
        case 98: {
          QuestflagTimer = input.ReadString();
          break;
        }
        case 106: {
          QuestflagRepeatTime = input.ReadString();
          break;
        }
        case 114: {
          LocationNpcStart = input.ReadString();
          break;
        }
        case 122: {
          LocationNpcEnd = input.ReadString();
          break;
        }
        case 130: {
          LocationQuestArea = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SecondaryAttribute : pb::IMessage<SecondaryAttribute>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SecondaryAttribute> _parser = new pb::MessageParser<SecondaryAttribute>(() => new SecondaryAttribute());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SecondaryAttribute> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PortalDatDBReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SecondaryAttribute() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SecondaryAttribute(SecondaryAttribute other) : this() {
    healthAttributeType_ = other.healthAttributeType_;
    healthAttributeDivisor_ = other.healthAttributeDivisor_;
    staminaAttributeType_ = other.staminaAttributeType_;
    staminaAttributeDivisor_ = other.staminaAttributeDivisor_;
    manaAttributeType_ = other.manaAttributeType_;
    manaAttributeDivisor_ = other.manaAttributeDivisor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SecondaryAttribute Clone() {
    return new SecondaryAttribute(this);
  }

  /// <summary>Field number for the "health_attribute_type" field.</summary>
  public const int HealthAttributeTypeFieldNumber = 1;
  private uint healthAttributeType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint HealthAttributeType {
    get { return healthAttributeType_; }
    set {
      healthAttributeType_ = value;
    }
  }

  /// <summary>Field number for the "health_attribute_divisor" field.</summary>
  public const int HealthAttributeDivisorFieldNumber = 2;
  private uint healthAttributeDivisor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint HealthAttributeDivisor {
    get { return healthAttributeDivisor_; }
    set {
      healthAttributeDivisor_ = value;
    }
  }

  /// <summary>Field number for the "stamina_attribute_type" field.</summary>
  public const int StaminaAttributeTypeFieldNumber = 3;
  private uint staminaAttributeType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StaminaAttributeType {
    get { return staminaAttributeType_; }
    set {
      staminaAttributeType_ = value;
    }
  }

  /// <summary>Field number for the "stamina_attribute_divisor" field.</summary>
  public const int StaminaAttributeDivisorFieldNumber = 4;
  private uint staminaAttributeDivisor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StaminaAttributeDivisor {
    get { return staminaAttributeDivisor_; }
    set {
      staminaAttributeDivisor_ = value;
    }
  }

  /// <summary>Field number for the "mana_attribute_type" field.</summary>
  public const int ManaAttributeTypeFieldNumber = 5;
  private uint manaAttributeType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ManaAttributeType {
    get { return manaAttributeType_; }
    set {
      manaAttributeType_ = value;
    }
  }

  /// <summary>Field number for the "mana_attribute_divisor" field.</summary>
  public const int ManaAttributeDivisorFieldNumber = 6;
  private uint manaAttributeDivisor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ManaAttributeDivisor {
    get { return manaAttributeDivisor_; }
    set {
      manaAttributeDivisor_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SecondaryAttribute);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SecondaryAttribute other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HealthAttributeType != other.HealthAttributeType) return false;
    if (HealthAttributeDivisor != other.HealthAttributeDivisor) return false;
    if (StaminaAttributeType != other.StaminaAttributeType) return false;
    if (StaminaAttributeDivisor != other.StaminaAttributeDivisor) return false;
    if (ManaAttributeType != other.ManaAttributeType) return false;
    if (ManaAttributeDivisor != other.ManaAttributeDivisor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HealthAttributeType != 0) hash ^= HealthAttributeType.GetHashCode();
    if (HealthAttributeDivisor != 0) hash ^= HealthAttributeDivisor.GetHashCode();
    if (StaminaAttributeType != 0) hash ^= StaminaAttributeType.GetHashCode();
    if (StaminaAttributeDivisor != 0) hash ^= StaminaAttributeDivisor.GetHashCode();
    if (ManaAttributeType != 0) hash ^= ManaAttributeType.GetHashCode();
    if (ManaAttributeDivisor != 0) hash ^= ManaAttributeDivisor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HealthAttributeType != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(HealthAttributeType);
    }
    if (HealthAttributeDivisor != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(HealthAttributeDivisor);
    }
    if (StaminaAttributeType != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(StaminaAttributeType);
    }
    if (StaminaAttributeDivisor != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(StaminaAttributeDivisor);
    }
    if (ManaAttributeType != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(ManaAttributeType);
    }
    if (ManaAttributeDivisor != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(ManaAttributeDivisor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HealthAttributeType != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(HealthAttributeType);
    }
    if (HealthAttributeDivisor != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(HealthAttributeDivisor);
    }
    if (StaminaAttributeType != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(StaminaAttributeType);
    }
    if (StaminaAttributeDivisor != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(StaminaAttributeDivisor);
    }
    if (ManaAttributeType != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(ManaAttributeType);
    }
    if (ManaAttributeDivisor != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(ManaAttributeDivisor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HealthAttributeType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HealthAttributeType);
    }
    if (HealthAttributeDivisor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HealthAttributeDivisor);
    }
    if (StaminaAttributeType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StaminaAttributeType);
    }
    if (StaminaAttributeDivisor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StaminaAttributeDivisor);
    }
    if (ManaAttributeType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ManaAttributeType);
    }
    if (ManaAttributeDivisor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ManaAttributeDivisor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SecondaryAttribute other) {
    if (other == null) {
      return;
    }
    if (other.HealthAttributeType != 0) {
      HealthAttributeType = other.HealthAttributeType;
    }
    if (other.HealthAttributeDivisor != 0) {
      HealthAttributeDivisor = other.HealthAttributeDivisor;
    }
    if (other.StaminaAttributeType != 0) {
      StaminaAttributeType = other.StaminaAttributeType;
    }
    if (other.StaminaAttributeDivisor != 0) {
      StaminaAttributeDivisor = other.StaminaAttributeDivisor;
    }
    if (other.ManaAttributeType != 0) {
      ManaAttributeType = other.ManaAttributeType;
    }
    if (other.ManaAttributeDivisor != 0) {
      ManaAttributeDivisor = other.ManaAttributeDivisor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          HealthAttributeType = input.ReadUInt32();
          break;
        }
        case 16: {
          HealthAttributeDivisor = input.ReadUInt32();
          break;
        }
        case 24: {
          StaminaAttributeType = input.ReadUInt32();
          break;
        }
        case 32: {
          StaminaAttributeDivisor = input.ReadUInt32();
          break;
        }
        case 40: {
          ManaAttributeType = input.ReadUInt32();
          break;
        }
        case 48: {
          ManaAttributeDivisor = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          HealthAttributeType = input.ReadUInt32();
          break;
        }
        case 16: {
          HealthAttributeDivisor = input.ReadUInt32();
          break;
        }
        case 24: {
          StaminaAttributeType = input.ReadUInt32();
          break;
        }
        case 32: {
          StaminaAttributeDivisor = input.ReadUInt32();
          break;
        }
        case 40: {
          ManaAttributeType = input.ReadUInt32();
          break;
        }
        case 48: {
          ManaAttributeDivisor = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PortalDatDB : pb::IMessage<PortalDatDB>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PortalDatDB> _parser = new pb::MessageParser<PortalDatDB>(() => new PortalDatDB());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PortalDatDB> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PortalDatDBReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PortalDatDB() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PortalDatDB(PortalDatDB other) : this() {
    attributeXp_ = other.attributeXp_.Clone();
    vitalXp_ = other.vitalXp_.Clone();
    trainedSkillXp_ = other.trainedSkillXp_.Clone();
    specializedSkillXp_ = other.specializedSkillXp_.Clone();
    characterLevelXp_ = other.characterLevelXp_.Clone();
    skills_ = other.skills_.Clone();
    contracts_ = other.contracts_.Clone();
    secondaryAttributes_ = other.secondaryAttributes_ != null ? other.secondaryAttributes_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PortalDatDB Clone() {
    return new PortalDatDB(this);
  }

  /// <summary>Field number for the "attributeXp" field.</summary>
  public const int AttributeXpFieldNumber = 1;
  private static readonly pb::FieldCodec<global::XpListElementInt> _repeated_attributeXp_codec
      = pb::FieldCodec.ForMessage(10, global::XpListElementInt.Parser);
  private readonly pbc::RepeatedField<global::XpListElementInt> attributeXp_ = new pbc::RepeatedField<global::XpListElementInt>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XpListElementInt> AttributeXp {
    get { return attributeXp_; }
  }

  /// <summary>Field number for the "vitalXp" field.</summary>
  public const int VitalXpFieldNumber = 2;
  private static readonly pb::FieldCodec<global::XpListElementInt> _repeated_vitalXp_codec
      = pb::FieldCodec.ForMessage(18, global::XpListElementInt.Parser);
  private readonly pbc::RepeatedField<global::XpListElementInt> vitalXp_ = new pbc::RepeatedField<global::XpListElementInt>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XpListElementInt> VitalXp {
    get { return vitalXp_; }
  }

  /// <summary>Field number for the "trainedSkillXp" field.</summary>
  public const int TrainedSkillXpFieldNumber = 3;
  private static readonly pb::FieldCodec<global::XpListElementInt> _repeated_trainedSkillXp_codec
      = pb::FieldCodec.ForMessage(26, global::XpListElementInt.Parser);
  private readonly pbc::RepeatedField<global::XpListElementInt> trainedSkillXp_ = new pbc::RepeatedField<global::XpListElementInt>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XpListElementInt> TrainedSkillXp {
    get { return trainedSkillXp_; }
  }

  /// <summary>Field number for the "specializedSkillXp" field.</summary>
  public const int SpecializedSkillXpFieldNumber = 4;
  private static readonly pb::FieldCodec<global::XpListElementInt> _repeated_specializedSkillXp_codec
      = pb::FieldCodec.ForMessage(34, global::XpListElementInt.Parser);
  private readonly pbc::RepeatedField<global::XpListElementInt> specializedSkillXp_ = new pbc::RepeatedField<global::XpListElementInt>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XpListElementInt> SpecializedSkillXp {
    get { return specializedSkillXp_; }
  }

  /// <summary>Field number for the "characterLevelXp" field.</summary>
  public const int CharacterLevelXpFieldNumber = 5;
  private static readonly pb::FieldCodec<global::XpListElementLong> _repeated_characterLevelXp_codec
      = pb::FieldCodec.ForMessage(42, global::XpListElementLong.Parser);
  private readonly pbc::RepeatedField<global::XpListElementLong> characterLevelXp_ = new pbc::RepeatedField<global::XpListElementLong>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::XpListElementLong> CharacterLevelXp {
    get { return characterLevelXp_; }
  }

  /// <summary>Field number for the "skills" field.</summary>
  public const int SkillsFieldNumber = 6;
  private static readonly pb::FieldCodec<global::Skill> _repeated_skills_codec
      = pb::FieldCodec.ForMessage(50, global::Skill.Parser);
  private readonly pbc::RepeatedField<global::Skill> skills_ = new pbc::RepeatedField<global::Skill>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Skill> Skills {
    get { return skills_; }
  }

  /// <summary>Field number for the "contracts" field.</summary>
  public const int ContractsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::Contract> _repeated_contracts_codec
      = pb::FieldCodec.ForMessage(58, global::Contract.Parser);
  private readonly pbc::RepeatedField<global::Contract> contracts_ = new pbc::RepeatedField<global::Contract>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Contract> Contracts {
    get { return contracts_; }
  }

  /// <summary>Field number for the "secondaryAttributes" field.</summary>
  public const int SecondaryAttributesFieldNumber = 8;
  private global::SecondaryAttribute secondaryAttributes_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SecondaryAttribute SecondaryAttributes {
    get { return secondaryAttributes_; }
    set {
      secondaryAttributes_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PortalDatDB);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PortalDatDB other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!attributeXp_.Equals(other.attributeXp_)) return false;
    if(!vitalXp_.Equals(other.vitalXp_)) return false;
    if(!trainedSkillXp_.Equals(other.trainedSkillXp_)) return false;
    if(!specializedSkillXp_.Equals(other.specializedSkillXp_)) return false;
    if(!characterLevelXp_.Equals(other.characterLevelXp_)) return false;
    if(!skills_.Equals(other.skills_)) return false;
    if(!contracts_.Equals(other.contracts_)) return false;
    if (!object.Equals(SecondaryAttributes, other.SecondaryAttributes)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= attributeXp_.GetHashCode();
    hash ^= vitalXp_.GetHashCode();
    hash ^= trainedSkillXp_.GetHashCode();
    hash ^= specializedSkillXp_.GetHashCode();
    hash ^= characterLevelXp_.GetHashCode();
    hash ^= skills_.GetHashCode();
    hash ^= contracts_.GetHashCode();
    if (secondaryAttributes_ != null) hash ^= SecondaryAttributes.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    attributeXp_.WriteTo(output, _repeated_attributeXp_codec);
    vitalXp_.WriteTo(output, _repeated_vitalXp_codec);
    trainedSkillXp_.WriteTo(output, _repeated_trainedSkillXp_codec);
    specializedSkillXp_.WriteTo(output, _repeated_specializedSkillXp_codec);
    characterLevelXp_.WriteTo(output, _repeated_characterLevelXp_codec);
    skills_.WriteTo(output, _repeated_skills_codec);
    contracts_.WriteTo(output, _repeated_contracts_codec);
    if (secondaryAttributes_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(SecondaryAttributes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    attributeXp_.WriteTo(ref output, _repeated_attributeXp_codec);
    vitalXp_.WriteTo(ref output, _repeated_vitalXp_codec);
    trainedSkillXp_.WriteTo(ref output, _repeated_trainedSkillXp_codec);
    specializedSkillXp_.WriteTo(ref output, _repeated_specializedSkillXp_codec);
    characterLevelXp_.WriteTo(ref output, _repeated_characterLevelXp_codec);
    skills_.WriteTo(ref output, _repeated_skills_codec);
    contracts_.WriteTo(ref output, _repeated_contracts_codec);
    if (secondaryAttributes_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(SecondaryAttributes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += attributeXp_.CalculateSize(_repeated_attributeXp_codec);
    size += vitalXp_.CalculateSize(_repeated_vitalXp_codec);
    size += trainedSkillXp_.CalculateSize(_repeated_trainedSkillXp_codec);
    size += specializedSkillXp_.CalculateSize(_repeated_specializedSkillXp_codec);
    size += characterLevelXp_.CalculateSize(_repeated_characterLevelXp_codec);
    size += skills_.CalculateSize(_repeated_skills_codec);
    size += contracts_.CalculateSize(_repeated_contracts_codec);
    if (secondaryAttributes_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SecondaryAttributes);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PortalDatDB other) {
    if (other == null) {
      return;
    }
    attributeXp_.Add(other.attributeXp_);
    vitalXp_.Add(other.vitalXp_);
    trainedSkillXp_.Add(other.trainedSkillXp_);
    specializedSkillXp_.Add(other.specializedSkillXp_);
    characterLevelXp_.Add(other.characterLevelXp_);
    skills_.Add(other.skills_);
    contracts_.Add(other.contracts_);
    if (other.secondaryAttributes_ != null) {
      if (secondaryAttributes_ == null) {
        SecondaryAttributes = new global::SecondaryAttribute();
      }
      SecondaryAttributes.MergeFrom(other.SecondaryAttributes);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          attributeXp_.AddEntriesFrom(input, _repeated_attributeXp_codec);
          break;
        }
        case 18: {
          vitalXp_.AddEntriesFrom(input, _repeated_vitalXp_codec);
          break;
        }
        case 26: {
          trainedSkillXp_.AddEntriesFrom(input, _repeated_trainedSkillXp_codec);
          break;
        }
        case 34: {
          specializedSkillXp_.AddEntriesFrom(input, _repeated_specializedSkillXp_codec);
          break;
        }
        case 42: {
          characterLevelXp_.AddEntriesFrom(input, _repeated_characterLevelXp_codec);
          break;
        }
        case 50: {
          skills_.AddEntriesFrom(input, _repeated_skills_codec);
          break;
        }
        case 58: {
          contracts_.AddEntriesFrom(input, _repeated_contracts_codec);
          break;
        }
        case 66: {
          if (secondaryAttributes_ == null) {
            SecondaryAttributes = new global::SecondaryAttribute();
          }
          input.ReadMessage(SecondaryAttributes);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          attributeXp_.AddEntriesFrom(ref input, _repeated_attributeXp_codec);
          break;
        }
        case 18: {
          vitalXp_.AddEntriesFrom(ref input, _repeated_vitalXp_codec);
          break;
        }
        case 26: {
          trainedSkillXp_.AddEntriesFrom(ref input, _repeated_trainedSkillXp_codec);
          break;
        }
        case 34: {
          specializedSkillXp_.AddEntriesFrom(ref input, _repeated_specializedSkillXp_codec);
          break;
        }
        case 42: {
          characterLevelXp_.AddEntriesFrom(ref input, _repeated_characterLevelXp_codec);
          break;
        }
        case 50: {
          skills_.AddEntriesFrom(ref input, _repeated_skills_codec);
          break;
        }
        case 58: {
          contracts_.AddEntriesFrom(ref input, _repeated_contracts_codec);
          break;
        }
        case 66: {
          if (secondaryAttributes_ == null) {
            SecondaryAttributes = new global::SecondaryAttribute();
          }
          input.ReadMessage(SecondaryAttributes);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
